// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPIgQmiHkbBhVqVLf7MEqF2b9LULAhMdc',
    appId: '1:302083874687:web:ec1654e3209a975c94844a',
    messagingSenderId: '302083874687',
    projectId: 'music-11z',
    authDomain: 'music-11z.firebaseapp.com',
    storageBucket: 'music-11z.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfcIylPn60owBz_q4v4sl1vcK-1cAL9UE',
    appId: '1:302083874687:android:0b96dee29fd78d2b94844a',
    messagingSenderId: '302083874687',
    projectId: 'music-11z',
    storageBucket: 'music-11z.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC2rLnpHeSab54ARVt5wRaG54KsotuCjA',
    appId: '1:302083874687:ios:3123893129e85a5c94844a',
    messagingSenderId: '302083874687',
    projectId: 'music-11z',
    storageBucket: 'music-11z.firebasestorage.app',
    iosBundleId: 'com.example.music',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDC2rLnpHeSab54ARVt5wRaG54KsotuCjA',
    appId: '1:302083874687:ios:3123893129e85a5c94844a',
    messagingSenderId: '302083874687',
    projectId: 'music-11z',
    storageBucket: 'music-11z.firebasestorage.app',
    iosBundleId: 'com.example.music',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPIgQmiHkbBhVqVLf7MEqF2b9LULAhMdc',
    appId: '1:302083874687:web:b58c1c9e8d70d26294844a',
    messagingSenderId: '302083874687',
    projectId: 'music-11z',
    authDomain: 'music-11z.firebaseapp.com',
    storageBucket: 'music-11z.firebasestorage.app',
  );
}
